[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38']
quiet = true
exclude='''
/(
    \.git
  | \.hg
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests
)/
'''

